### ISSUE TITLE
Suverene kart! Har dere tenkt på en 2024 versjon?

### ISSUE THREAD

**Issue by LarsXOS** [robhop/fylker-og-kommuner#3]
Nå skjer det kommune- og fylkessplitt i 2024, vil dere lage oppdatert versjon? 

Fantastiske kart, bruker de ofte!

**Comment by robhop** [comment]
Så kjekt å høre at kartet blir brukt :-)
Jeg laget dette kun fordi jeg var så skuffet over at kartverket ikke laget et praktisk kart over kommuner og fylker som vanlige folk/utviklere enkelt kunne bruke. Gjort helt uten noe mer mål og mening enn det. Så jeg kan ikke love noe.
Har ikke tenkte så mye på nye versjoner eller oppdateringer, det beste hadde vært om kartverket gjorde det. Jeg tror det bare mangler litt på viljen.

**Comment by runesandnes** [comment]
Har dere noen tips på hvordan man bruker kartene fra Kartverket? 

På https://kartkatalog.geonorge.no/metadata/administrative-enheter-kommuner/041f1e6e-bdbc-4091-b48f-8a5990f3cc5b får du lastet ned oppdaterte kart i GeoJSON, og så kan du forenkle og konvertere med https://mapshaper.org/

MEN disse kartene er med kommune/fylkesgrenser, og ikke faktisk kystlinjen. Det gjør at kystkommuner ikke ser bra ut, Lofoten blir en klump etc. Er det noe jeg ikke har forstått med disse kartene, eller finnes det annen kilde?

**Comment by robhop** [comment]
Hei Rune. 
Det er ikke lett å gi tips uten å vite litt mer hva du er ute etter. Problemet du beskriver er jo grunnen til at jeg i utgangspunktet laget dette repoet. Kartdata for administrasjons-grenser er ikke klippet etter kyst fordi grensene ikke stopper ved strandlinjen, så enkelt er det. 
Det betyr at du enten må  klippe administrasjons-grensene etter et karltag som har kystlinjer, + rydde en hel masse i alt rotet det genererer. 

Tips?
* https://gdal.org/drivers/vector/sosi.html
* https://www.uib.no/utdanning/evu/120878/gis-geografiske-informasjonssystem-og-geovisualisering
* https://qgis.org/en/site/index.html#
* Mye tid :-/

**Comment by robhop** [comment]
> Nå skjer det kommune- og fylkessplitt i 2024, vil dere lage oppdatert versjon?
> 
> Fantastiske kart, bruker de ofte!

Ikke helt ferdig, men skal være brukanes data der for 2024
https://github.com/robhop/norway-geojson

**Comment by robhop** [comment]
Nå skal oppdatere kart for 2024 være på plass.
